version: '2'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  node-chrome:
    build:
      context: "."
      dockerfile: "Dockerfile.node-chrome-ja"
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  node-firefox:
    build:
      context: "."
      dockerfile: "Dockerfile.node-firefox-ja"
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
