# 事前に build.sh でlibが作成されていること
version: '3'
services:
  scenario-test:
    build:
      context: "."
      dockerfile: "dockerfiles/dev/Dockerfile"
    volumes:
      - ./dockerfiles/dev/entry-point.sh:/root/scenario-test/entry-point.sh
      - ./screenTestProj/src:/root/scenario-test/src
      - ./screenTestProj/pom.xml:/root/scenario-test/pom.xml
      - ./screenTestProj/target:/root/scenario-test/target
      - ../scenario-data:/root/scenario-test/build

networks:
  default:
    external:
      name: runtimeenv_test_bridge
